Add step to test `ecc`/`ecli` cli, and the corresponding docker image (#265)
* Add step to test `ecc` cli

* Add workflow to test the docker image of `ecc`

* Fix yaml syntax

* Fix CI

* Fix CI

* Update ecc.yml

* Fix test for ecc-image

* Fix ecc image test

* Add test for ecli CLI (partially)

* Fix ecc image test

* Fix ecli cli test

* Fix ecli test

* Fix ecli test

* Fix CLI test

* Fix CI

* Fix CI

* Add cli test for native only client

* Fix ci

* Add step to test ecli-server

diff --git a/.github/workflows/ecc-image.yml b/.github/workflows/ecc-image.yml
--- a/.github/workflows/ecc-image.yml
+++ b/.github/workflows/ecc-image.yml
@@ -46,6 +46,20 @@ jobs:
           tags: |
             ghcr.io/${{ env.REPO_OWNER }}/ecc-x86_64:latest
           push: true
+      - name: Test the docker image (x86_64)
+        run: |
+          sudo apt-get update
+          sudo apt-get remove moby-containerd moby-runc 
+          sudo apt-get install -y docker.io
+          mkdir docker-test
+          cd docker-test
+          cp ../.github/assets/simple.bpf.c .
+          docker run -v `pwd`/:/src/ ghcr.io/${{ env.REPO_OWNER }}/ecc-x86_64:latest
+          if [[ ! -f "./package.json" ]]
+          then
+            echo "Docker image failed to produce package.jso"
+            exit 1
+          fi
 
       - name: Build ecc-aarch64 image and push to GitHub Container Registry
         uses: docker/build-push-action@v2
